Di: Di_Parser_Dependency Class Reference
Di_Parser_Dependency Class Reference
Public Member Functions
__construct ($annotationParser=null, $mode=self::MODE_ANNOTATION)
setAnnotationParser (Di_Parser_Annnotation $annotationParser)
getAnnotationParser ()
setMode ($mode=self::MODE_ANNOTATION)
getMode ()
parse ($range=self::RANGE_EVERYTHING, $single=null)
Data Fields
const MODE_ANNOTATION = 1
const MODE_TYPEHINT = 2
const RANGE_EVERYTHING = 1
const RANGE_CLASS = 2
const RANGE_METHODS = 3
const RANGE_PROPERTIES = 4
const RANGE_SINGLE_ELEMENT = 5
Private Member Functions
_parseFromReflectionByRange (ReflectionClass $reflection, $range, $single=null)
_parseFromClassComment (ReflectionClass $reflection)
_parseFromClassMethods (ReflectionClass $reflection)
_parseFromClassProperties (ReflectionClass $reflection)
_queryParser ($input)
_parseAnnotationsFromComment ($comment)
_includeFile ($file)
Private Attributes
$_annotationParser
$_mode
$_identifier
Detailed Description
Definition at line 77 of file Dependency.php.
Constructor & Destructor Documentation
__construct ($ annotationParser = null, $ mode = self::MODE_ANNOTATION)
Constructor
Constructor of this class
Parameters:
mixed $annotationParser An optional annotation parser instance
integer $mode The mode used to parse dependenciess
Returns:
void public
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 143 of file Dependency.php.
Member Function Documentation
_includeFile ($ file) [private]
Loads a file into sope
This method is intend to load a file into scope.
Parameters:
string $file The file to load (include)
Returns:
void protected
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Exceptions:
Di_Exception
Definition at line 453 of file Dependency.php.
_parseAnnotationsFromComment ($ comment) [private]
Dispatches a comment to the Annotation Parser and returns the result
This method is intend to dispatch a comment to the Annotation Parser and return the result.
Parameters:
string $comment The comment to parse annotations from
Returns:
array Containing the dependencies build from annotations private
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 430 of file Dependency.php.
_parseFromClassComment (ReflectionClass $ reflection) [private]
Parses the dependencies from a given reflection out of the class' comment
This method is intend to parse the dependencies from a given reflection out of the class' comment.
Parameters:
ReflectionClass $reflection The reflection instance to parse from
Returns:
array An raw array containing the dependencies indexed private
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 331 of file Dependency.php.
References _queryParser().
_parseFromClassMethods (ReflectionClass $ reflection) [private]
Parses the dependencies from a given reflection out of the class' methods
This method is intend to parse the dependencies from a given reflection out of the class' methods.
Parameters:
ReflectionClass $reflection The reflection instance to parse from
Returns:
array An raw array containing the dependencies indexed private
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 349 of file Dependency.php.
References _queryParser().
_parseFromClassProperties (ReflectionClass $ reflection) [private]
Parses the dependencies from a given reflection out of the class' properties
This method is intend to parse the dependencies from a given reflection out of the class' properties.
Parameters:
ReflectionClass $reflection The reflection instance to parse from
Returns:
array An raw array containing the dependencies indexed private
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 380 of file Dependency.php.
References _queryParser().
_parseFromReflectionByRange (ReflectionClass $ reflection, $ range, $ single = null) [private]
Parses the dependencies from a given reflection for defined range and optional method or property
This method is intend to parse the dependencies from a given reflection for defined range and optional method or property.
Parameters:
ReflectionClass $reflection The reflection instance to parse from
integer $range The range to parse from
string $single The (optional) name of a method or property to parse from
Returns:
array An raw array containing the dependencies indexed private
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 284 of file Dependency.php.
References _parseFromClassComment(), _parseFromClassMethods(), and _parseFromClassProperties().
_queryParser ($ input) [private]
Dispatches calls to annotation parser
This method is intend to dispatch calls to annotation parser.
Parameters:
string $input The input to parse from
Returns:
array An array containing the dependencies or an empty one private
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 411 of file Dependency.php.
References Di_Parser_Abstract\$input.
getAnnotationParser ()
Returns the annotation parser instance
This method is intend to return the annotation parser instance.
Returns:
Di_Parser_Annnotation The annotation parser instance public
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 185 of file Dependency.php.
References $_annotationParser.
getMode ()
Returns the mode used to retrieve dependencies
This method is intend to return the mode used to retrieve dependencies.
Returns:
integer The mode used to retrieve dependencies public
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 221 of file Dependency.php.
References $_mode.
parse ($ range = self::RANGE_EVERYTHING, $ single = null)
Parses the dependencies
This method is intend to parse the dependencies.
Parameters:
integer $range The range to parse from
string $single The name of a single method, property ...
Returns:
array An raw array containing the dependencies indexed by its public
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Exceptions:
Di_Exception
Definition at line 241 of file Dependency.php.
References Di_Parser_Abstract\$input, _includeFile(), _parseFromReflectionByRange(), and Di_Parser_Abstract\getInput().
setAnnotationParser (Di_Parser_Annnotation $ annotationParser)
Returns the annotation parser instance
This method is intend to return the annotation parser instance.
Parameters:
Di_Parser_Annnotation $annotationParser An instance of the annotation parser
Returns:
void public
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 169 of file Dependency.php.
setMode ($ mode = self::MODE_ANNOTATION)
Sets the mode used to retrieve dependencies
This method is intend to set the mode used to retrieve dependencies. This can be either MODE_ANNOTATION if you want to parse dependencies from annotation, or MODE_TYPEHINT if you prefer parsing dependencies from typehints.
Parameters:
integer $mode The mode to set
Returns:
void public
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 205 of file Dependency.php.
Field Documentation
$_annotationParser [private]
Definition at line 85 of file Dependency.php.
$_identifier [private]
Definition at line 101 of file Dependency.php.
$_mode [private]
Definition at line 93 of file Dependency.php.
const MODE_ANNOTATION = 1
Definition at line 109 of file Dependency.php.
const MODE_TYPEHINT = 2
Definition at line 110 of file Dependency.php.
const RANGE_CLASS = 2
Definition at line 119 of file Dependency.php.
const RANGE_EVERYTHING = 1
Definition at line 118 of file Dependency.php.
const RANGE_METHODS = 3
Definition at line 120 of file Dependency.php.
const RANGE_PROPERTIES = 4
Definition at line 121 of file Dependency.php.
const RANGE_SINGLE_ELEMENT = 5
Definition at line 122 of file Dependency.php.
The documentation for this class was generated from the following file:
Di/Parser/Dependency.php