Di: Di_Factory Class Reference
Di_Factory Class Reference
Public Member Functions
build ($classname, $dependencies=null)
construct ($classname, array $arguments=array())
Private Member Functions
_instanciateWithDependencies ($classname, $setup)
_instanciateWithoutDependencies ($classname, array $arguments=array())
_createInstance ($classname, array $arguments=array(), array $injections=array())
_constructorInjection ($classname, array $arguments)
_setterInjection (&$instance, array $injections)
_propertyInjection (&$instance, array $injections)
_parseInjections ($type, array $injections)
_mergeArguments (array $injections, array $arguments)
_initEmptyInjectionContainer ()
Private Attributes
$_reflector
$_instanciable
$_constructor
Detailed Description
Definition at line 75 of file Factory.php.
Member Function Documentation
_constructorInjection ($ classname, array $ arguments) [private]
Returns an instance with injected dependencies
This method is intend to return an instance of the given class. It injects the required dependencies into constructor on instanciation.
Parameters:
string $classname The name of the class to instanciate
array $arguments The arguments to pass to constructor
Returns:
object The new created instance private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 371 of file Factory.php.
References construct().
_createInstance ($ classname, array $ arguments = array(), array $ injections = array()) [private]
Instanciates a class and process the optional arguments and injections
This method is intend to instanciate a class and pass the required dependencies to it. The depencies are preconfigured and passed to this method as $setup. The classname is the name of the class to instanciate and arguments is an (optional) array of arguments which are passed to the class as additional arguments when instanciating.
Parameters:
string $classname The name of the class to instanciate
array $arguments The arguments to pass to constructo
array $injections The injections to process
Returns:
object The new created instance private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 304 of file Factory.php.
References _constructorInjection(), _mergeArguments(), _parseInjections(), _propertyInjection(), _setterInjection(), Di_Dependency::TYPE_CONSTRUCTOR, Di_Dependency::TYPE_METHOD, and Di_Dependency::TYPE_PROPERTY.
_initEmptyInjectionContainer () [private]
Creates and returns an empty array for the three types of injections
This method is intend to create and return an empty array for the three types of injections.
Returns:
array For the three types of injections private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 531 of file Factory.php.
_instanciateWithDependencies ($ classname, $ setup) [private]
Instanciates a class including it dependencies
This method is intend to instanciate a class and pass the required dependencies to it. The depencies are preconfigured and passed to this method as $setup. The classname is the name of the class to instanciate and arguments is an (optional) array of arguments which are passed to the class as additional arguments when instanciating.
Parameters:
string $classname The name of the class to instanciate
array $setup The setup for instanciating (contains array of depencies, arguments, ...)
Returns:
object The new created instance private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 212 of file Factory.php.
References _createInstance(), _initEmptyInjectionContainer(), and construct().
_instanciateWithoutDependencies ($ classname, array $ arguments = array()) [private]
Instanciates a class without further dependencies
This method is intend to instanciate a class. The classname is the name of the class to instanciate and arguments is an (optional) array of arguments which are passed to the class as additional arguments when instanciating.
Parameters:
string $classname The name of the class to instanciate
mixed $arguments Can be either a list of additional arguments passed to constructor when instance get created or NULL if no arguments needed (default = null)
Returns:
object The new created instance private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 281 of file Factory.php.
References _createInstance().
_mergeArguments (array $ injections, array $ arguments) [private]
Merges given constructor injections and arguments for constructor
This method is intend to merge injections and arguments for constructor.
Parameters:
array $injections The injection arguments to pass to constructor
array $arguments The additional arguments to pass to constructor
Returns:
array The merged result ready to pass to targets constructor private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 486 of file Factory.php.
_parseInjections ($ type, array $ injections) [private]
Parses out the requqested type of injection from list of injections
This method is intend to parse out the requqested type of injection from list of injections.
Parameters:
string $type The type of injection (can be of: constructor, setter, property)
array $injections The dependencies to parse from
Returns:
mixed NULL if no dependencies found, otherwise ARRAY containing the dependencies private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 442 of file Factory.php.
References Di_Dependency::TYPE_CONSTRUCTOR, Di_Dependency::TYPE_METHOD, and Di_Dependency::TYPE_PROPERTY.
_propertyInjection (&$ instance, array $ injections) [private]
Injects given dependencies through properties
This method is intend to injects given dependencies through properties.
Parameters:
string &$instance The instance to inject dependencies to
array $injections The dependencies to inject as array
Returns:
void private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 421 of file Factory.php.
_setterInjection (&$ instance, array $ injections) [private]
Injects given dependencies through setters
This method is intend to injects given dependencies through setters.
Parameters:
string &$instance The instance to inject dependencies to
array $injections The dependencies to inject as array
Returns:
void private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 400 of file Factory.php.
build ($ classname, $ dependencies = null)
Instanciates a class without further dependencies
This method is intend to instanciate a class. The classname is the name of the class to instanciate and arguments is an (optional) array of arguments which are passed to the class as additional arguments when instanciating.
Parameters:
string $classname The name of the class to instanciate
array $dependencies The complete setup of dependencies
Returns:
object The new instance public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 125 of file Factory.php.
References _instanciateWithDependencies(), and _instanciateWithoutDependencies().
construct ($ classname, array $ arguments = array())
Constructs an instance of a given class
This method is intend to construct an instance of a given class and pass the given (optional) arguments to the constructor. This method looks really ugly and i know this of course. But this way is a tradeoff between functionality and speed optimization.
Parameters:
string $classname The name of the class to instanciate
array $arguments The arguments to pass to constructor
Returns:
object Instance of given class(name) public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Exceptions:
Di_Exception
Definition at line 165 of file Factory.php.
Field Documentation
$_constructor [private]
Definition at line 102 of file Factory.php.
$_instanciable [private]
Definition at line 93 of file Factory.php.
$_reflector [private]
Definition at line 84 of file Factory.php.
The documentation for this class was generated from the following file:
C:/Program Files/xampp/htdocs/Di/Lib/Di/Factory.php