Di: Di_Container Class Reference
Di_Container Class Reference
Public Member Functions
setMap (Di_Map $map, $override=true)
getMap ()
getMapFromOtherNamespace ($namespace)
importMapFromOtherNamespace ($namespace)
setFactory (Di_Factory $factory)
getFactory ()
build ($classname, $arguments=null)
Static Public Member Functions
requirementsFulfilled ()
static getInstance ($namespace=self::DEFAULT_NAMESPACE, $mode=self::MODE_STATIC)
Data Fields
const DEFAULT_NAMESPACE = 'Di'
const MODE_STATIC = 1
const MODE_DYNAMIC = 2
Private Member Functions
_mergeMaps (Di_Map $target, Di_Map $source)
__construct ($namespace, $mode)
Private Attributes
$_namespace
$_mode
$_factory
Static Private Attributes
static $_instances = array()
static $_dependencyMaps = array()
Detailed Description
Definition at line 77 of file Container.php.
Constructor & Destructor Documentation
__construct ($ namespace, $ mode) [private]
Constructor
This method is the constructor.
Parameters:
string $namespace The namespace to operate
integer $mode The mode used to handle maps
Returns:
Di_Container The current instance of the Container for chaining/fluent-interface public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 431 of file Container.php.
Member Function Documentation
_mergeMaps (Di_Map $ target, Di_Map $ source) [private]
merges a new map with existing one
This method is intend to merge an already existing map with a new one.s
Parameters:
Di_Map $target The map in which the $source is merged into
Di_Map $source The map which is merged into $target
Returns:
Di_Container The current instance of the Container for chaining/fluent-interface private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 403 of file Container.php.
References Di_Map::export(), and Di_Map::import().
build ($ classname, $ arguments = null)
Constructs all single parts and returns a new instance
This method is intend to combine all defined dependencies and returns a instance of requested class.
Parameters:
string $classname The name of the class to build
mixed $arguments Arguments to pass to class (works only in dynamic mode)
Returns:
object Instance of the given class public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Exceptions:
Di_Exception
Definition at line 290 of file Container.php.
References getFactory(), getMap(), and requirementsFulfilled().
getFactory ()
Getter for Factory
This method is intend to return the instance of Di_Factory
Returns:
mixed The instance of Di_Factory if set, otherwise NULL public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 269 of file Container.php.
static getInstance ($ namespace = self::DEFAULT_NAMESPACE, $ mode = self::MODE_STATIC) [static]
Singleton Constructor
This method is intend to construct and return a singleton instance of Di_Container. Each container singleton is bound to a namespace (eg. 'default'). By passing a namespace through argument $namespace you are able to create more than one instance of container if needed/required by your application.
Parameters:
string $namespace The namespace of the Di_Container instance
integer $mode The mode used to handle maps
Returns:
Di_Container Instance public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 373 of file Container.php.
getMap ()
Returns the dependency map of this container
This method is intend to return the dependency map instance of this container instance.
Returns:
Di_Map The dependency map instance as Di_Map if set, otherwise NULL public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 189 of file Container.php.
getMapFromOtherNamespace ($ namespace)
Returns the Dependency-Map from another namespace
This method is intend to return the Dependency-Map of another namespace.
Parameters:
string $namespace The namespace to load map from
Returns:
Di_Map The dependency instance from another namespace public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Exceptions:
Di_Exception
Definition at line 210 of file Container.php.
importMapFromOtherNamespace ($ namespace)
Imports a Dependency-Map from another namespace
This method is intend to import a Dependency-Map from another namespace.
Parameters:
string $namespace The namespace to load dependency map from
Returns:
void public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 235 of file Container.php.
References getMapFromOtherNamespace().
requirementsFulfilled () [static]
Checks if the requirements are fulfilled
This method is intend to check if the requirements are fulfilled.
Returns:
boolean TRUE if requirements fulfilled, otherwise FALSE public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 341 of file Container.php.
References getMap().
setFactory (Di_Factory $ factory)
Setter for Factory
This method is intend to set the instance of Di_Factory
Parameters:
Di_Factory $factory The factory instance to set
Returns:
void public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 253 of file Container.php.
setMap (Di_Map $ map, $ override = true)
Adds a Di_Map to an existing Map by merging it in
This method is intend to merge a new Di_Map with an existing one.
Parameters:
Di_Map $map The map to merge in
boolean $override TRUE to override the existing map, FALSE to merge the maps
Returns:
void public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 160 of file Container.php.
References _mergeMaps(), and getMap().
Field Documentation
$_dependencyMaps = array() [static, private]
Definition at line 111 of file Container.php.
$_factory [private]
Definition at line 119 of file Container.php.
$_instances = array() [static, private]
Definition at line 86 of file Container.php.
$_mode [private]
Definition at line 102 of file Container.php.
$_namespace [private]
Definition at line 94 of file Container.php.
const DEFAULT_NAMESPACE = 'Di'
Definition at line 127 of file Container.php.
const MODE_DYNAMIC = 2
Definition at line 139 of file Container.php.
const MODE_STATIC = 1
Definition at line 138 of file Container.php.
The documentation for this class was generated from the following file:
C:/Program Files/xampp/htdocs/Di/Lib/Di/Container.php