Di: Di_Parser_Typehint Class Reference
Di_Parser_Typehint Class Reference
Public Member Functions
__construct (Di_Parser_Constructor $parser)
parse ()
Static Public Member Functions
requirementsFulfilled ()
Private Member Functions
_parseTypehints (ReflectionClass $reflectionClass, $sourcecode)
_signatureToArray ($method, $signature, $cleanup=true)
Private Attributes
$_parser
Detailed Description
Definition at line 77 of file Typehint.php.
Constructor & Destructor Documentation
__construct (Di_Parser_Constructor $ parser)
Definition at line 83 of file Typehint.php.
Member Function Documentation
_parseTypehints (ReflectionClass $ reflectionClass, $ sourcecode) [private]
Parses the typehints out of input and return the dependencies based on it as array
This method is intend to parse the typehints for the given reflection instance and the sourcecode.
Parameters:
ReflectionClass $reflectionClass An instance of ReflectionClass
string $sourcecode The sourcecode to parse typehints from
Returns:
array Containing the dependencies build from typehints public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Exceptions:
Di_Exception
Definition at line 158 of file Typehint.php.
References _signatureToArray(), Di_Parser_Abstract::getDefaultSekeleton(), Di_Dependency::TYPE_CONSTRUCTOR, and Di_Dependency::TYPE_METHOD.
_signatureToArray ($ method, $ signature, $ cleanup = true) [private]
Parses a given signature of a method for arguments and returns result as array
This method is intend to parse a given signature of a method for arguments and returns result as array.
Parameters:
string $method The name of the method to parse signature of
string $signature The signature to parse
boolean $cleanup TRUE to direct cleanup the result and store only arguments with typehint
Returns:
array Containing the parsed arguments and method name private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 253 of file Typehint.php.
parse ()
Parses the typehints out of input and return the dependencies based on it as array
This method is intend to ...
Returns:
array Containing the dependencies build from typehints public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Exceptions:
Di_Exception
Implements Di_Parser_Interface.
Definition at line 106 of file Typehint.php.
References _parseTypehints(), Di_Parser_Abstract::prepareInput(), and requirementsFulfilled().
requirementsFulfilled () [static]
Checks if the requirements are fulfilled
This method is intend to check if the requirements are fulfilled.
Returns:
boolean TRUE if requirements fulfilled, otherwise FALSE public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 229 of file Typehint.php.
Field Documentation
$_parser [private]
Definition at line 80 of file Typehint.php.
The documentation for this class was generated from the following file:
C:/Program Files/xampp/htdocs/Di/Lib/Di/Parser/Typehint.php