Di: Di_Map Class Reference
Di_Map Class Reference
Public Member Functions
setCollection (Di_Collection $collection)
getCollection ()
setNamespace ($namespace)
getNamespace ()
import (Di_Collection $collection)
export ()
wire ($mode=self::WIRE_MODE_AUTOMATIC, array $matrix=array())
reset ()
Data Fields
const WIRE_MODE_MANUAL = 1
const WIRE_MODE_AUTOMATIC = 2
const DEFAULT_NAMESPACE = 'Di'
Protected Member Functions
addRawDependenciesToCollection ($classname, array $rawDependencies)
Protected Attributes
$namespace = self::DEFAULT_NAMESPACE
$collection
$dependency
$parser
Private Member Functions
_wireClassWithDependencies (array $matrix)
_retrieveGlobals ()
Detailed Description
Definition at line 74 of file Map.php.
Member Function Documentation
_retrieveGlobals () [private]
Returns all variables from global scope
This method is intend to return all variables from PHP's global scope.
Returns:
array The defined variables from global scope private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 391 of file Map.php.
_wireClassWithDependencies (array $ matrix) [private]
Wires the map with given (existing) instances
This method is used to wire the instances given via arguments $matrix with the corresponding Id's from the static map.
Parameters:
array $matrix The matrix containing the instances for wiring (id => instance)
Returns:
void private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Exceptions:
Di_Exception (non-PHPdoc)
See also:
Di_Importer_Interface::wire()
Definition at line 350 of file Map.php.
References $dependency.
addRawDependenciesToCollection ($ classname, array $ rawDependencies) [protected]
Adds the given raw dependencies (array) to the collection for given classname
This method is intend to add the given raw dependencies (array) to the collection for given classname.
Parameters:
string $classname The name of the class the dependencies belong to
array $rawDependencies The dependencies as raw array
Returns:
void protected
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 305 of file Map.php.
References $dependency, and getCollection().
export ()
Exports a collection of dependencies
This method is intend to export a collection of dependencies (Di_Collection)
Returns:
Di_Collection A collection of dependencies public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 230 of file Map.php.
getCollection ()
Returns the collection of the map instance
This method is intend to return the collection (Di_Collection) of this map instance.
Returns:
mixed Di_Collection if set, otherwise NULL public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 162 of file Map.php.
getNamespace ()
Returns the identifier of the map instance
This method is intend to return the identifier of the map instance.
Returns:
string The namespace of this instance public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 196 of file Map.php.
import (Di_Collection $ collection)
Imports a collection of dependencies
This method is intend to import a collection of dependencies (Di_Collection)
Parameters:
Di_Collection $collection An instance of
Returns:
void public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 214 of file Map.php.
References $collection.
reset ()
Resets the state of this class
This method is intend to reset the state of this class. Currently only used for unit-testing.
Returns:
void public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 282 of file Map.php.
setCollection (Di_Collection $ collection)
Sets the collection of the map instance
This method is intend to set the collection (Di_Collection) of this map instance.
Parameters:
Di_Collection $collection The collection to set
Returns:
void public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 145 of file Map.php.
setNamespace ($ namespace)
Sets the identifier of the map instance
This method is intend to set the identifier of the map instance.
Parameters:
string $namespace The identifier to set
Returns:
void public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 180 of file Map.php.
References $namespace.
wire ($ mode = self::WIRE_MODE_AUTOMATIC, array $ matrix = array())
Wires existing instances of classes
This method is intend to connect existing instances from argument $matrix or retrieved from globals with the existing map. This connection is identified by the "id" in the map and the "key" in the array.
Parameters:
integer $mode This can be either WIRE_MODE_MANUAL or WIRE_MODE_AUTOMATIC
array $matrix A matrix defining the relation between an Id and an Instance as key => value pair
Returns:
boolean TRUE on success, otherwise FALSE public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Exceptions:
Di_Exception
Reimplemented in Di_Map_Fluent.
Definition at line 252 of file Map.php.
References _retrieveGlobals(), and _wireClassWithDependencies().
Field Documentation
$collection [protected]
Definition at line 90 of file Map.php.
$dependency [protected]
Definition at line 98 of file Map.php.
$namespace = self::DEFAULT_NAMESPACE [protected]
Definition at line 82 of file Map.php.
$parser [protected]
Definition at line 106 of file Map.php.
const DEFAULT_NAMESPACE = 'Di'
Definition at line 125 of file Map.php.
const WIRE_MODE_AUTOMATIC = 2
Definition at line 117 of file Map.php.
const WIRE_MODE_MANUAL = 1
Definition at line 116 of file Map.php.
The documentation for this class was generated from the following file:
C:/Program Files/xampp/htdocs/Di/Lib/Di/Map.php