Di: Di_Map_Fluent Class Reference
Di_Map_Fluent Class Reference
Public Member Functions
__construct (Di_Collection $collection, Di_Dependency $dependency)
generate ()
classname ($classname, $arguments=null, $constructor=null)
dependsOn ($classname)
identifier ($identifier)
id ($identifier)
instance ($instance)
configuration (array $configuration)
arguments (array $arguments)
setLastProcessedClass ($classname)
getLastProcessedClass ()
wire ($mode=self::WIRE_MODE_AUTOMATIC, array $matrix=array())
store ($returnContainer=true)
build ($arguments=null, $classname=null, $wire=true)
Private Member Functions
_reset ()
_flush ()
Private Attributes
$_classname
$_lastClassname
$_dependency
$_current
Detailed Description
Definition at line 78 of file Fluent.php.
Constructor & Destructor Documentation
__construct (Di_Collection $ collection, Di_Dependency $ dependency)
Constructor
Constructor of this class
Parameters:
Di_Collection $collection An instance of Di_Collection used to store dependencies in
Di_Dependency $dependency An instance of Di_Dependency used as base object for cloning new dependencies
Returns:
void public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 131 of file Fluent.php.
Member Function Documentation
_flush () [private]
Flushes the content
This method is intend to flush the temporary content.
Returns:
void private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 481 of file Fluent.php.
_reset () [private]
Resets the state of this instance to default
This method is intend to set the configuration of the dependency class.
Returns:
void private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 464 of file Fluent.php.
arguments (array $ arguments)
Setter for the arguments of the dependency class
This method is intend to set the arguments of the dependency class.
Parameters:
array $arguments The arguments to set
Returns:
Di_Map_Fluent Instance of this class (for method chaining) public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 324 of file Fluent.php.
build ($ arguments = null, $ classname = null, $ wire = true)
Shortcut for build()
This method is intend to act as a shortcut to build().
Parameters:
array $arguments The arguments to pass to build()
string $classname The (optional) name of the class to build instance of
boolean $wire TRUE to automatic wire instances, otherwise FALSE to do not
Returns:
Di_Map_Fluent Instance of this class (for method chaining) public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 437 of file Fluent.php.
References store(), wire(), and Di_Map::WIRE_MODE_AUTOMATIC.
classname ($ classname, $ arguments = null, $ constructor = null)
Setter for the name of the class which has dependencies
This method is intend to set the name of the class which has dependencies.
Parameters:
string $classname The name of the class which has dependencies
mixed $arguments The arguments to pass to constructor of class
mixed $constructor The constructor of the class
Returns:
Di_Map_Fluent Instance of this class (for method chaining) public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 176 of file Fluent.php.
References _flush().
configuration (array $ configuration)
Setter for the configuration of the dependency class
This method is intend to set the configuration of the dependency class.
Parameters:
array $configuration The configuration to set
Returns:
Di_Map_Fluent Instance of this class (for method chaining) public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 302 of file Fluent.php.
dependsOn ($ classname)
Setter for the name of the dependency class
This method is intend to set the name of the dependency class.
Parameters:
string $classname The name of the dependency class
Returns:
Di_Map_Fluent Instance of this class (for method chaining) public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 211 of file Fluent.php.
References _flush().
generate ()
Empty container method to keep the interface consistent with other Di_Map_* classes
This method is intend as empty container method to keep the interface consistent with other Di_Map_* classes.
Returns:
Di_Map_Fluent The current instance for chaining method calls public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 154 of file Fluent.php.
getLastProcessedClass ()
Returns the name of the last processed class
This method is intend to return the name of the last processed class
Returns:
string The name of the last processed class public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 362 of file Fluent.php.
id ($ identifier)
Setter for the identifier of the dependency class
This method is intend to set the identifier of the dependency class.
Parameters:
string $identifier The identifier of the dependency class
Returns:
Di_Map_Fluent Instance of this class (for method chaining) public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 262 of file Fluent.php.
References identifier().
identifier ($ identifier)
Setter for the identifier of the dependency class
This method is intend to set the identifier of the dependency class.
Parameters:
string $identifier The identifier of the dependency class
Returns:
Di_Map_Fluent Instance of this class (for method chaining) public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 240 of file Fluent.php.
instance ($ instance)
Setter for the instance of the dependency class
This method is intend to set the instance of the dependency class.
Parameters:
mixed $instance The instance to set
Returns:
Di_Map_Fluent Instance of this class (for method chaining) public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 280 of file Fluent.php.
setLastProcessedClass ($ classname)
Stores the name of the last processed class
This method is required for the fluent interface.
Parameters:
string $classname The name of the last processed class
Returns:
void public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 346 of file Fluent.php.
store ($ returnContainer = true)
Setter for the configuration of the dependency class
This method is intend to set the configuration of the dependency class.
Parameters:
boolean $returnContainer TRUE to return container instance, FALSE to return map instance
Returns:
Di_Container Instance of the container for active namespace public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 405 of file Fluent.php.
References _reset().
wire ($ mode = self::WIRE_MODE_AUTOMATIC, array $ matrix = array())
Shortcut to Di_Map::wire()
This method is a shortcut to Di_Map::wire().
Parameters:
integer $mode The mode to use for wiring
array $matrix The wire matrix containing instances to wire
Returns:
Di_Map_Fluent Instance of this class (for method chaining) public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Reimplemented from Di_Map.
Definition at line 381 of file Fluent.php.
References _flush().
Field Documentation
$_classname [private]
Definition at line 86 of file Fluent.php.
$_current [private]
Definition at line 110 of file Fluent.php.
$_dependency [private]
Definition at line 102 of file Fluent.php.
$_lastClassname [private]
Definition at line 94 of file Fluent.php.
The documentation for this class was generated from the following file:
C:/Program Files/xampp/htdocs/Di/Lib/Di/Map/Fluent.php