Di: Di_Collection Class Reference
Di_Collection Class Reference
Public Member Functions
addDependency ($classname, Di_Dependency $dependency)
addDependencies ($classname, array $dependencies)
addArguments ($classname, array $arguments)
getArguments ($classname)
setConstructor ($classname, $constructor)
getConstructor ($classname)
getSetup ($classname)
getDependencies ($classname)
rewind ()
current ()
key ()
next ()
valid ()
offsetExists ($offset)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetUnset ($offset)
Private Member Functions
_initIndexByTarget ($target)
_initIndexByDependency ($dependency)
Private Attributes
$_position = 0
$_numericalIndex
$_arguments = array()
$_constructor = array()
$_indexByTarget = array()
$_indexByDependency = array()
Detailed Description
Definition at line 74 of file Collection.php.
Member Function Documentation
_initIndexByDependency ($ dependency) [private]
Inits the index - Index by Dependency
This method is intend to init the index by dependency.
Parameters:
string $dependency The name of the class
Returns:
void private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 473 of file Collection.php.
_initIndexByTarget ($ target) [private]
Inits the index - Index by Target
This method is intend to init the index by target.
Parameters:
string $target The name of the class
Returns:
void private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 452 of file Collection.php.
addArguments ($ classname, array $ arguments)
Adds arguments of a target to collection
This method is intend to add arguments of a target to collection.
Parameters:
string $classname The name of the class to add arguments for
array $arguments The arguments to add
Returns:
void public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 214 of file Collection.php.
addDependencies ($ classname, array $ dependencies)
Adds an array of dependencies to collection
This method is intend to add an array of dependencies to the collection of dependencies.
Parameters:
string $classname The name of the class which depends on the $dependency
array $dependencies The dependency setup as Di_Dependency object
Returns:
boolean TRUE on success, otherwise FALSE public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Exceptions:
Di_Exception
Definition at line 182 of file Collection.php.
References addDependency().
addDependency ($ classname, Di_Dependency $ dependency)
Adds a dependency to collection
This method is intend to add a dependency to the collection of dependencies.
Parameters:
string $classname The name of the class which depends on the $dependency
Di_Dependency $dependency The dependency setup as Di_Dependency object
Returns:
boolean TRUE on success, otherwise FALSE public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 146 of file Collection.php.
References _initIndexByDependency(), _initIndexByTarget(), and Di_Dependency::getClassname().
current ()
Implements current
Returns:
mixed current element from array
Definition at line 347 of file Collection.php.
getArguments ($ classname)
Returns the arguments of a target
This method is intend to return the arguments of a target.
Parameters:
string $classname The name of the class to return arguments for
Returns:
mixed Arguments as array, or NULL if no arguments set public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 232 of file Collection.php.
getConstructor ($ classname)
Getter for constructor
This method is intend to return the name of the constructor method of the target class.
Parameters:
string $classname The name of the class to return constructor for
Returns:
mixed STRING name of the constructor method if set, otherwise NULL public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 273 of file Collection.php.
getDependencies ($ classname)
Returns the dependencies for given classname
This method is intend to return the dependencies for given classname.
Parameters:
string $classname The name of the class to lookup dependencies for
Returns:
mixed Di_Dependency if dependency is set, otherwise NULL public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 321 of file Collection.php.
getSetup ($ classname)
Returns the setup by a given target
This method is intend to return the setup of a target.
Parameters:
string $classname The name of the class to return setup for
Returns:
mixed Arguments as array, or NULL if no arguments set public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 293 of file Collection.php.
key ()
Implements key
Returns:
mixed The current key as INTEGER or STRING (depends on array)
Definition at line 357 of file Collection.php.
next ()
Implements next
Returns:
void
Definition at line 367 of file Collection.php.
offsetExists ($ offset)
Implements offsetExists
Parameters:
string $offset The offset to check
Returns:
boolean TRUE if offset is set, otherwise FALSE
Definition at line 393 of file Collection.php.
offsetGet ($ offset)
Implements offsetGet
Parameters:
string $offset The offset to return
Returns:
mixed The data from offset
Definition at line 405 of file Collection.php.
offsetSet ($ offset, $ value)
Implements offsetSet
Parameters:
string $offset The offset to set
mixed $value The value to set
Returns:
void
Definition at line 418 of file Collection.php.
offsetUnset ($ offset)
Implements offsetUnset
Parameters:
string $offset The offset to unset
Returns:
void
Definition at line 430 of file Collection.php.
rewind ()
Implements rewind
Returns:
void
Definition at line 337 of file Collection.php.
setConstructor ($ classname, $ constructor)
Setter for constructor
This method is intend to set the name of the constructor method of the target class.
Parameters:
string $classname The name of the class to set constructor for
string $constructor The name of the constructor method
Returns:
void public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 254 of file Collection.php.
valid ()
Implements valid
Returns:
boolean TRUE if current element exists, otherwise FALSE
Definition at line 377 of file Collection.php.
Field Documentation
$_arguments = array() [private]
Definition at line 99 of file Collection.php.
$_constructor = array() [private]
Definition at line 108 of file Collection.php.
$_indexByDependency = array() [private]
Definition at line 124 of file Collection.php.
$_indexByTarget = array() [private]
Definition at line 116 of file Collection.php.
$_numericalIndex [private]
Definition at line 91 of file Collection.php.
$_position = 0 [private]
Definition at line 82 of file Collection.php.
The documentation for this class was generated from the following file:
C:/Program Files/xampp/htdocs/Di/Lib/Di/Collection.php