Di: Di_Parser_Annnotation Class Reference
Di_Parser_Annnotation Class Reference
Public Member Functions
parse ()
hasCommand ()
numberOfCommands ()
Static Public Member Functions
requirementsFulfilled ()
Data Fields
const BASE_PATTERN = 'DiInject'
Private Member Functions
_getDefaultSekeleton ()
Detailed Description
Definition at line 76 of file Annotation.php.
Member Function Documentation
_getDefaultSekeleton () [private]
Returns the default skeleton for storing a dependency
This method returns the default skeleton for storing a dependency.
Returns:
array An array containing the default skeleton public
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 238 of file Annotation.php.
hasCommand ()
Checks if the string has a DiInject command
This method is intend to check if a given string contains a DiInject command.
Returns:
array Containing the dependencies build from annotations public
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 182 of file Annotation.php.
numberOfCommands ()
Returns the count of DiInject commands
This method is intend to return the count of DiInject commands from last parsing.
Returns:
integer The count of commands found public
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 199 of file Annotation.php.
parse ()
Parses the annotations out of input and return it as array
This method is intend to build an array of options for each of the commands that were matched. This options array is readable/similar to a dependency map item. This method requires only argument one ($identifier) to work properly.
Returns:
array Containing the dependencies build from annotations public
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Exceptions:
Di_Exception
Todo:
Refactor!
Implements Di_Parser_Interface.
Definition at line 106 of file Annotation.php.
References _getDefaultSekeleton(), hasCommand(), and requirementsFulfilled().
requirementsFulfilled () [static]
Checks if the requirements are fulfilled
This method is intend to check if the requirements are fulfilled.
Returns:
boolean TRUE if requirements fulfilled, otherwise FALSE public
Author:
Benjamin Carl opens.nosp@m.ourc.nosp@m.e@cli.nosp@m.ckal.nosp@m.iciou.nosp@m.s.de
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 218 of file Annotation.php.
Field Documentation
const BASE_PATTERN = 'DiInject'
Definition at line 84 of file Annotation.php.
The documentation for this class was generated from the following file:
Di/Parser/Annotation.php