Di: Di_Parser_Annotation Class Reference
Di_Parser_Annotation Class Reference
Public Member Functions
parse ($range=self::RANGE_EVERYTHING)
hasCommand ()
numberOfCommands ()
Static Public Member Functions
requirementsFulfilled ()
Data Fields
const BASE_PATTERN = 'DiInject'
const RANGE_EVERYTHING = 1
const RANGE_CLASS = 2
const RANGE_METHODS = 3
const RANGE_PROPERTIES = 4
const RANGE_SINGLE_ELEMENT = 5
Private Member Functions
_parseFromReflectionByRange (ReflectionClass $reflection, $range)
_getAnnotationFromSource ($sourcecode)
_parseFromClassComment (ReflectionClass $reflection)
_parseFromClassMethods (ReflectionClass $reflection)
_parseFromClassProperties (ReflectionClass $reflection)
Detailed Description
Definition at line 76 of file Annotation.php.
Member Function Documentation
_getAnnotationFromSource ($ sourcecode) [private]
Parses the annotations out of input and return it as array
This method is intend to build an array of options for each of the commands that were matched. This options array is readable/similar to a dependency map item.
Parameters:
string $sourcecode The sourcecode to parse annotations from
Returns:
array Containing the dependencies parsed from annotations found private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 274 of file Annotation.php.
References Di_Parser_Abstract::getDefaultSekeleton(), and hasCommand().
_parseFromClassComment (ReflectionClass $ reflection) [private]
Parses the dependencies from a given reflection out of the class' comment
This method is intend to parse the dependencies from a given reflection out of the class' comment.
Parameters:
ReflectionClass $reflection The reflection instance to parse from
Returns:
array An raw array containing the dependencies indexed private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 344 of file Annotation.php.
References _getAnnotationFromSource().
_parseFromClassMethods (ReflectionClass $ reflection) [private]
Parses the dependencies from a given reflection out of the class' methods
This method is intend to parse the dependencies from a given reflection out of the class' methods.
Parameters:
ReflectionClass $reflection The reflection instance to parse from
Returns:
array An raw array containing the dependencies indexed private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 362 of file Annotation.php.
References _getAnnotationFromSource().
_parseFromClassProperties (ReflectionClass $ reflection) [private]
Parses the dependencies from a given reflection out of the class' properties
This method is intend to parse the dependencies from a given reflection out of the class' properties.
Parameters:
ReflectionClass $reflection The reflection instance to parse from
Returns:
array An raw array containing the dependencies indexed private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 394 of file Annotation.php.
References _getAnnotationFromSource().
_parseFromReflectionByRange (ReflectionClass $ reflection, $ range) [private]
Parses the dependencies from a given reflection for defined range and optional method or property
This method is intend to parse the dependencies from a given reflection for defined range and optional method or property.
Parameters:
ReflectionClass $reflection The reflection instance to parse from
integer $range The range to parse from
Returns:
array An raw array containing the dependencies indexed private
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 226 of file Annotation.php.
References _parseFromClassComment(), _parseFromClassMethods(), and _parseFromClassProperties().
hasCommand ()
Checks if the string has a DiInject command
This method is intend to check if a given string contains a DiInject command.
Returns:
array Containing the dependencies build from annotations public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 163 of file Annotation.php.
numberOfCommands ()
Returns the count of DiInject commands
This method is intend to return the count of DiInject commands from last parsing.
Returns:
integer The count of commands found public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 180 of file Annotation.php.
parse ($ range = self::RANGE_EVERYTHING)
Parses the annotations out of input and return it as array
This method is intend to build an array of options for each of the commands that were matched. This options array is readable/similar to a dependency map item. This method requires only argument one ($identifier) to work properly.
Parameters:
integer $range The range to parse from
Returns:
array Containing the dependencies build from annotations public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Exceptions:
Di_Exception
Definition at line 119 of file Annotation.php.
References Di_Parser_Abstract::$input, _parseFromReflectionByRange(), Di_Parser_Abstract::getInput(), Di_Parser_Abstract::loadFile(), and requirementsFulfilled().
requirementsFulfilled () [static]
Checks if the requirements are fulfilled
This method is intend to check if the requirements are fulfilled.
Returns:
boolean TRUE if requirements fulfilled, otherwise FALSE public
Author:
Benjamin Carl <opensource@clickalicious.de>
Since:
Method available since Release 1.0.0
Version:
1.0
Definition at line 202 of file Annotation.php.
Field Documentation
const BASE_PATTERN = 'DiInject'
Definition at line 84 of file Annotation.php.
const RANGE_CLASS = 2
Definition at line 93 of file Annotation.php.
const RANGE_EVERYTHING = 1
Definition at line 92 of file Annotation.php.
const RANGE_METHODS = 3
Definition at line 94 of file Annotation.php.
const RANGE_PROPERTIES = 4
Definition at line 95 of file Annotation.php.
const RANGE_SINGLE_ELEMENT = 5
Definition at line 96 of file Annotation.php.
The documentation for this class was generated from the following file:
C:/Program Files/xampp/htdocs/Di/Lib/Di/Parser/Annotation.php